### ISSUE TITLE
shop/urls.py

### ISSUE THREAD

**Issue by almazkun** [henrymbuguak/Shopping-Cart-Using-Django-2.0-and-Python-3.6#1]
On your web page (https://academy.muva.tech/blog/lesson-4-defining-url-patterns-template-shop-products-django-2-0-python-3-6/) section with URL is missing. 

![Screenshot_2019-05-22 Lesson 4 Defining Url patterns and template for Our Shop products in Django 2 0 and Python 3 6 - Muva](https://user-images.githubusercontent.com/20808565/58165217-285cd300-7ca9-11e9-83c8-0a75bef7d22e.png)

**Comment by henrymbuguak** [comment]
Hello @almazkun we will update the tutorial, thank you for reaching out.

Here is the link to that file:
https://github.com/muvatech/Shopping-Cart-Using-Django-2.0-and-Python-3.6/blob/master/shop/urls.py
